### ISSUE TITLE
Partial flashing fails when the code needs more than 255 packets sent

### ISSUE THREAD

**Issue by martinwork** [microbit-sam/microbit-dal#16]
When the packet number sequence byte wraps past 255 to 0, the partial flashing service does not respond. This happens when flashing the gol sample over the untitled one in the attached zip. My trace is below.

I think the test that is causing the problem is (packetNum < packetCount) in flashData. Both numbers are unsigned bytes. packetCount starts as zero and the first packetNum sent is 1 because it must fail the test (packetNum != ++packetCount). That is, packetNum must be must be equal to 1+packetCount.

So I think the sequence of (packetNum,packetCount) pairs will be (1,0), (2,1), (3,2)... (255,254), (0,255). At this point (packetNum < packetCount) is true, the flashData function just returns and the client doesn't receive a FLASH_DATA reply notification.

[sams pf files 180605.zip](https://github.com/microbit-sam/microbit-dal/files/2077519/sams.pf.files.180605.zip)

pflashFlashNext pflashAddr 30800 pflashIdx 0 pflashBin.length 1110
pflashFlashNext addr 30800
pflashFlashNext packet 0 bytes 01 08 00 01
pflashFlashNext packet 1 bytes 01 00 03 02
pflashFlashNext packet 2 bytes 01 00 03 03
pflashFlashNext packet 3 bytes 01 00 03 04
didUpdateValueForCharacteristic
pflashReceived
pflashReceived pflashReasonStatus pflashReasonFlash
pflashReceived pflashReasonStatus pflashReasonFlash pflash_OK
pflashFlashNext pflashAddr 30800 pflashIdx 40 pflashBin.length 1110
pflashFlashNext addr 30840
pflashFlashNext packet 0 bytes 01 08 40 05
pflashFlashNext packet 1 bytes 01 00 03 06
pflashFlashNext packet 2 bytes 01 00 03 07
pflashFlashNext packet 3 bytes 01 00 03 08

[...more batches of 4 packets...]

pflashReceived
pflashReceived pflashReasonStatus pflashReasonFlash
pflashReceived pflashReasonStatus pflashReasonFlash pflash_OK
pflashFlashNext pflashAddr 30800 pflashIdx fc0 pflashBin.length 1110
pflashFlashNext addr 317c0
pflashFlashNext packet 0 bytes 01 17 c0 fd
pflashFlashNext packet 1 bytes 01 00 03 fe
pflashFlashNext packet 2 bytes 01 00 03 ff
pflashFlashNext packet 3 bytes 01 00 03 00

**Comment by martinwork** [comment]
@microbit-sam Am I doing something wrong with the packet number byte?

**Comment by microbit-sam** [comment]
@martinwork I think you're right about the test being wrong. I'm going to take sometime this afternoon to have a look and make sense of it

**Comment by microbit-sam** [comment]
Had a quick look at this, does starting from 0 and changing to this make sense?
Can't see why I would've started from 1... https://xkcd.com/163/

```
  if(packetNum != packetCount)
        {
            uint8_t flashNotificationBuffer[] = {FLASH_DATA, 0xAA};
            ble.gattServer().notify(partialFlashCharacteristicHandle, (const uint8_t *)flashNotificationBuffer, sizeof(flashNotificationBuffer));
            packetCount = blockPacketCount + 3;
            blockNum = 0;
            return;
        } else {
           packetCount++;
       }
```

**Comment by martinwork** [comment]
That's a good idea - the ++packetCount has always made my head hurt! I think +3 now needs to be +4, because you no longer have to allow for the ++packetCount. And we still need to test for packetNum being before packetCount, meaning the packet needs to be ignored rather than faulted. How about something like the code below? 

```
  if ( packetNum != packetCount)
  {
    if ( packetNum < packetCount ? packetCount - packetNum < 8 : packetNum - packetCount > 248)
      return; // packet is from a previous batch

    uint8_t flashNotificationBuffer[] = {FLASH_DATA, 0xAA};
    ble.gattServer().notify(partialFlashCharacteristicHandle, (const uint8_t *)flashNotificationBuffer, sizeof(flashNotificationBuffer));
    packetCount = blockPacketCount + 4;
    blockNum = 0;
    return;
  }

  packetCount++;
```

**Comment by microbit-sam** [comment]
Yep - I like it! I'll make this change and get updated docs up
Thanks Martin!

**Comment by martinwork** [comment]
@microbit-sam In the version you're merging you still have  the (packetNum < packetCount) test, so the bug will still be there.
https://github.com/microbit-sam/microbit-dal/blob/master/source/bluetooth/MicroBitPartialFlashingService.cpp#L182

**Comment by microbit-sam** [comment]
OK - removed that
Aiming to build and test this before the end of the week - I've got a few hours travelling on Friday afternoon when I can hopefully work on improving the docs

**Comment by microbit-sam** [comment]
This has been fixed since
